language: node_js
node_js:
  - "lts/*"
  - "node"
before_install:
  - gem install jekyll
install: npm ci
script: npm run build

# branch whitelist
branches:
  only:
    - master     # test the gh-pages branch
    - gh-pages     # test the gh-pages branch

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
