version: '3.1'

services:
  build:
    image: jekyll/jekyll:pages
    volumes:
      - ./:/srv/jekyll
    command: jekyll build

  serve:
    image: jekyll/jekyll:pages
    volumes:
      - ./:/srv/jekyll
    ports:
      - 4000:4000
    command: jekyll serve --watch --incremental --drafts
