version: '2.0'

services:
  jekyll:
    image: jekyll/jekyll:pages
    ports:
        - 4000:4000
    volumes:
        - .:/srv/jekyll

  build:
    extends:
      service: jekyll
    command: jekyll build

  serve:
    extends:
      service: jekyll
    command: jekyll serve --watch --incremental --drafts
